### ISSUE TITLE
Fix "Antora Doc / Deploy GitHub Pages (pull_request)" action on PR

### ISSUE THREAD

**Issue by mcanevet** [camptocamp/camptocamp-devops-stack#124]
Maybe we should not even run it?

**Comment by acampergue-camptocamp** [comment]
I agree on the fact that we shouldn't run it anyway, since we want to keep the documentation in sync with what is in the master branch.
But it might be interesting to see where the problem we started to have yesterday came from, because I didn't have it in the previous MR.
`/usr/bin/git push --force ***github.com/camptocamp/camptocamp-devops-stack.git gh-action-temp-deployment-branch:gh-pages
remote: Permission to camptocamp/camptocamp-devops-stack.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/camptocamp/camptocamp-devops-stack.git/': The requested URL returned error: 403`
